apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec: 
  selector: 
    app: nginx-pod
  ports:
    - name: web
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-pod
        image: nginx
        env:
        - name: MY_TYPE
          value: nginx
        ports:
        - containerPort: 80
